### ISSUE TITLE
autogen.sh should not call configure

### ISSUE THREAD

**Issue by wdlkmpx** [rocky/vcdimager#9]
The current behavior is not good, IMO.

Configure should be able to detect when the autoconf files have changed and trigger a reconfiguration, this happens when maintainer mode is disabled and is annoying

Autogen.sh is also used to create  a release tarball, just by running it the code is ready to be packaged.
 it's also possible to add extra lines to automate the creation of a release tarball - 0 effort

**Comment by rocky** [comment]
I don't see a problem. autogen.sh is a convention that is used. What goes into it is the implementor's choice. 

Unless you can show me someplace that promotes your theory of how people are supposed to write packages and what should and should not go into autogen.sh, it stays the way it is. Until then, just read and follow the directions. 

If you write software and package something and want to use autogen.sh using some other conventions, go right ahead.

**Comment by wdlkmpx** [comment]
Well, I have a replacement that is generic as well.

I use it in several other projects, then when I want to release a new version, I just type 
./autogen.sh release 
and a new release tarball is ready and the source tree is clean

If there's interest I can integrate it into this project, meanwhile I'll open a new PR with essential fixes

**Comment by rocky** [comment]
> If there's interest I can integrate it into this project, meanwhile I'll open a new PR with essential fixes

I'd like to pass on this. I just don't see this as a problem so much as a convention you use.

**Comment by wdlkmpx** [comment]
Well there is a fundamental problem when building from git

This is one of the few projects that makes autogen call configure, it's unorthodox, that behavior is not expected by my scripts 

I've seen many autogen.sh scripts, most don't call configure, except a few that haven't been updated in decades, overall this project has a Jurassic feel

 I run configure with specific params for each project, that behavior is being eradicated one app at a time

**Comment by rocky** [comment]
Two can play this game: from my side it feels like a fundamental problem with wdlkmpx. In all of these years and all of the packages I've written, no one has brought this up. Yes, I guess once upon a time this is the way packages roamed. vcdimager if you haven't noticed is kind of a Jurassic kind of package. 

Packagers who package Jurassic packages need to adapt to those conditions.

**Comment by wdlkmpx** [comment]
You're right, some changes introduce issues that packagers need to deal with. Although this stuff is relatively harmless, it just requires probably one minor adjustment.

I see some changes I plan to make have already been made ... and reverted. The bitfield stuff.

I think this project supports only gcc (probably clang too) and GNU make, any other combination is probably untested and unsupported, so a minor  cleanup is probably a good idea

I'm interested in reducing the configure time, to build the same package in 20 architectures, completely static. vcdimager doesn't compile on Debian Stretch (2017) with the system libcdio, so overall some updates wouldn't harm the project

 So I guess I'll just spend this afternoon making some changes and pushing them to my fork to produce the desired tarball, changes that may be of interest sometime in the future
